### ISSUE TITLE
some documentation or example?

### ISSUE THREAD

**Issue by ptheofan** [SAM-IT/yii2-abac#1]

**Comment by SamMousa** [comment]
I'll type something up tomorrow!

**Comment by SamMousa** [comment]
Or wel... asap

In the meantime, check this out: https://github.com/SAM-IT/abac/
This library is only a wrapper for yii2. The actual library is in the other repo and it has some documentation.

**Comment by SamMousa** [comment]
@ptheofan, I'm sorry I don't have the bandwidth to write up docs. You can also have a look at this project that uses this adapter and the underlying library for all of it's authorization.

https://github.com/HeRAMS-WHO/herams-backend
